name: Block Labeled PR Merges

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  prevent-merge:
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request label prevents merging."
          echo "Labels: ${{ join(github.event.*.labels.*.name, ', ') }}"
          echo "Remove the blocking label(s) to skip this check."
          exit 1
