name: Block Labeled PR Merges

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  prevent-merge:
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
            if echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | grep -q 'do not merge'; then
            echo "::error::Pull request has 'do not merge' label"
            exit 1
            fi
