name: Merge Protection

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled] # Trigger on these PR events

jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "do not merge" label
        id: check_for_do_not_merge_label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name.toLowerCase());
            const forbiddenLabel = "do not merge"; 

            if (labels.includes(forbiddenLabel)) {
              core.setFailed(`PR has the "${forbiddenLabel}" label. Merging is blocked.`);
            } else {
              console.log(`PR does not have the "${forbiddenLabel}" label. Merging is allowed.`);
            }
